FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm install

# Copy frontend source
COPY frontend .

# Build Vite project
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY target /usr/share/nginx/html/target
COPY frontend/config /usr/share/nginx/html/config
EXPOSE 80